using System;
using System.IO;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace foxhole_artillery_calculator.classes
{
    /// <summary>
    /// Manages application configuration
    /// </summary>
    public class ConfigurationManager
    {
        private static readonly string ConfigFileName = "config.yaml";
        private static readonly string ConfigFilePath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "FoxholeArtilleryCalculator",
            ConfigFileName
        );

        private static AppConfiguration _instance;

        /// <summary>
        /// Gets the current configuration instance
        /// </summary>
        public static AppConfiguration Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = LoadConfiguration();
                }
                return _instance;
            }
        }

        /// <summary>
        /// Loads configuration from file or creates default if not exists
        /// </summary>
        private static AppConfiguration LoadConfiguration()
        {
            try
            {
                // Ensure the directory exists
                string directory = Path.GetDirectoryName(ConfigFilePath);
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                // If config file doesn't exist, create it with defaults
                if (!File.Exists(ConfigFilePath))
                {
                    var defaultConfig = new AppConfiguration();
                    SaveConfiguration(defaultConfig);
                    return defaultConfig;
                }

                // Read and deserialize the configuration
                string yaml = File.ReadAllText(ConfigFilePath);
                var deserializer = new DeserializerBuilder()
                    .WithNamingConvention(UnderscoredNamingConvention.Instance)
                    .IgnoreUnmatchedProperties()
                    .Build();

                var config = deserializer.Deserialize<AppConfiguration>(yaml);
                return config ?? new AppConfiguration();
            }
            catch (Exception ex)
            {
                // Log error to file for troubleshooting
                LogError("Error loading configuration", ex);
                return new AppConfiguration();
            }
        }

        /// <summary>
        /// Saves configuration to file
        /// </summary>
        public static void SaveConfiguration(AppConfiguration config)
        {
            try
            {
                // Ensure the directory exists
                string directory = Path.GetDirectoryName(ConfigFilePath);
                if (!Directory.Exists(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                // Serialize and write the configuration
                var serializer = new SerializerBuilder()
                    .WithNamingConvention(UnderscoredNamingConvention.Instance)
                    .Build();

                string yaml = serializer.Serialize(config);

                // Add header comment
                string header = @"# Foxhole Artillery Calculator Configuration
# This file is automatically generated on first startup with default values
# You can customize hotkeys and other settings here
# 
# Available hotkeys (use VKey names from KeyboardHook.VKeys enum):
# Numpad keys: NUMPAD0-NUMPAD9, ADD, SUBTRACT, MULTIPLY, DIVIDE, DECIMAL
# Function keys: F1-F24
# Other keys: SNAPSHOT (PrtScr), INSERT, DELETE, HOME, END, PRIOR (PageUp), NEXT (PageDown)
# Letters: KEY_A through KEY_Z
# Numbers: KEY_0 through KEY_9
# Arrow keys: UP, DOWN, LEFT, RIGHT
# Special: SPACE, RETURN (Enter), ESCAPE, TAB, BACK (Backspace)
# Modifiers: SHIFT, CONTROL, MENU (Alt)
# 
# For a full list of available keys, see classes/KeyboardHook.cs in the source code
#

";
                File.WriteAllText(ConfigFilePath, header + yaml);
            }
            catch (Exception ex)
            {
                // Log error to file for troubleshooting
                LogError("Error saving configuration", ex);
            }
        }

        /// <summary>
        /// Logs error to a file for troubleshooting
        /// </summary>
        private static void LogError(string message, Exception ex)
        {
            try
            {
                string directory = Path.GetDirectoryName(ConfigFilePath);
                string logFilePath = Path.Combine(directory, "error.log");
                string logMessage = $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss}] {message}: {ex.Message}\n{ex.StackTrace}\n\n";
                File.AppendAllText(logFilePath, logMessage);
            }
            catch
            {
                // If we can't log, just fail silently - this is a best-effort logging
                System.Diagnostics.Debug.WriteLine($"{message}: {ex.Message}");
            }
        }

        /// <summary>
        /// Reloads configuration from file
        /// </summary>
        public static void ReloadConfiguration()
        {
            _instance = LoadConfiguration();
        }

        /// <summary>
        /// Gets the configuration file path
        /// </summary>
        public static string GetConfigFilePath()
        {
            return ConfigFilePath;
        }

        /// <summary>
        /// Parses a hotkey string to VKeys enum
        /// </summary>
        public static KeyboardHook.VKeys ParseHotkey(string hotkeyString)
        {
            if (string.IsNullOrWhiteSpace(hotkeyString))
            {
                throw new ArgumentException("Hotkey string cannot be empty");
            }

            if (Enum.TryParse<KeyboardHook.VKeys>(hotkeyString, true, out var vkey))
            {
                return vkey;
            }

            throw new ArgumentException($"Invalid hotkey: {hotkeyString}");
        }
    }
}
